### ISSUE TITLE
error while installing ReactionDecoder in Debian 9 "Stretch"

### ISSUE THREAD

**Issue by diaspj** [asad/ReactionDecoder#10]
ERROR INFORMATION:

root@bn:~/Programs_software/ReactionDecoder-master# mvn -DskipTests=true install
[INFO] Scanning for projects...
[WARNING] The project uk.ac.ebi.rdt:rdt:jar:2.2.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] -------------------------< uk.ac.ebi.rdt:rdt >--------------------------
[INFO] Building rdt 2.2.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rdt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/Programs_software/ReactionDecoder-master/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ rdt ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rdt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 23240 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ rdt ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ rdt ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ rdt ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ rdt ---
[INFO] Installing /root/Programs_software/ReactionDecoder-master/target/rdt-2.2.0-SNAPSHOT.jar to /root/.m2/repository/uk/ac/ebi/rdt/rdt/2.2.0-SNAPSHOT/rdt-2.2.0-SNAPSHOT.jar
[INFO] Installing /root/Programs_software/ReactionDecoder-master/pom.xml to /root/.m2/repository/uk/ac/ebi/rdt/rdt/2.2.0-SNAPSHOT/rdt-2.2.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.963 s
[INFO] Finished at: 2019-06-04T11:25:22+01:00
[INFO] ------------------------------------------------------------------------
root@bn:~/Programs_software/ReactionDecoder-master# mvn install
[INFO] Scanning for projects...
[WARNING] The project uk.ac.ebi.rdt:rdt:jar:2.2.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] -------------------------< uk.ac.ebi.rdt:rdt >--------------------------
[INFO] Building rdt 2.2.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rdt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/Programs_software/ReactionDecoder-master/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ rdt ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rdt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 23240 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ rdt ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ rdt ---
[INFO] Surefire report directory: /root/Programs_software/ReactionDecoder-master/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running uk.ac.bioinception.SMILES2AAMTest
uk.ac.ebi.reactionblast.mechanism.ReactionMechanismTool WARN: Unmapped atoms present in this reaction(MAX) algorithm.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.412 sec
Running uk.ac.ebi.aamtool.RXNMappingTest
Mapping Reaction R00011
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R00014
Mapping Reaction R00023
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R00025
Mapping Reaction R00045
Mapping Reaction R00093
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R00097
uk.ac.ebi.reactionblast.mechanism.ReactionMechanismTool WARN: Unmapped atoms present in this reaction(MIN) algorithm.
uk.ac.ebi.reactionblast.mechanism.ReactionMechanismTool WARN: Unmapped atoms present in this reaction(MAX) algorithm.
uk.ac.ebi.reactionblast.mechanism.ReactionMechanismTool WARN: Unmapped atoms present in this reaction(MIXTURE) algorithm.
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R00114
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
formedCleavedWFingerprint
ID=R00114:Bond Cleaved and Formed (5)
[C-H:2.0, C-N:2.0, C-O:1.0, C=O:1.0, H-O:1.0]

Mapping Reaction R00307
Mapping Reaction R00344
Mapping Reaction R00630
Mapping Reaction R00959
Mapping Reaction R01015
Mapping Reaction R01068
Mapping Reaction R01081
Mapping Reaction R01145
Mapping Reaction R01148
Mapping Reaction R01394
Mapping Reaction R01432
Mapping Reaction R01518
Mapping Reaction R01529
Mapping Reaction R01557
Mapping Reaction R01569
Mapping Reaction R01715
Mapping Reaction R01717
Mapping Reaction R01819
Mapping Reaction R01903
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R02007
Mapping Reaction R02555
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R02707
Mapping Reaction R02718
Mapping Reaction R02918
Mapping Reaction R02996
Mapping Reaction R03020
Mapping Reaction R03063
Mapping Reaction R03187
Mapping Reaction R03332
Mapping Reaction R03364
Mapping Reaction R03627
Mapping Reaction R03673
Mapping Reaction R03959
Mapping Reaction R03979
Mapping Reaction R04165
Mapping Reaction R04333
Mapping Reaction R04538
Mapping Reaction R04558
Mapping Reaction R05069
Mapping Reaction R05071
Mapping Reaction R05137
Mapping Reaction R05217
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R05219
Mapping Reaction R05421
Mapping Reaction R05645
Mapping Reaction R06361
Mapping Reaction R06989
Mapping Reaction R07322
Mapping Reaction R07393
Mapping Reaction R07635
Mapping Reaction R07965
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R08639
Mapping Reaction R08761
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction R09087
Mapping Reaction aromaticity_check
Mapping Reaction R01561
Mapping Reaction R01194
Mapping Reaction R01188
Mapping Reaction 204
uk.ac.ebi.reactionblast.tools.MappingUtility ERROR: SEVERE Failed to generate image: Container has no bonds.
Mapping Reaction 25405
Mapping Reaction R00004
Tests run: 70, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 487.307 sec <<< FAILURE!
R04558(uk.ac.ebi.aamtool.RXNMappingTest)  Time elapsed: 2.631 sec  <<< FAILURE!
java.lang.AssertionError: expected:<4> but was:<5>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at uk.ac.ebi.aamtool.RXNMappingTest.R04558(RXNMappingTest.java:1035)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.openscience.smsd.mcs.MCSTest
MCS C1OC(CO)C(O)C1O
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 63.373 sec

Results :

Failed tests:   R04558(uk.ac.ebi.aamtool.RXNMappingTest): expected:<4> but was:<5>

Tests run: 86, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:20 min
[INFO] Finished at: 2019-06-04T11:34:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project rdt: There are test failures.
[ERROR]
[ERROR] Please refer to /root/Programs_software/ReactionDecoder-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by asad** [comment]
Thanks.
Please try with these two commands
5) mvn -P local clean install -DskipTests=true (fast single jar compilation, skip test)
6) mvn -P local clean install (single jar compilation with test)
