### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 10 at org.openscience.cdk.AtomContainer.getAtom(AtomContainer.java:294)

### ISSUE THREAD

**Issue by rmtfleming** [asad/ReactionDecoder#11]
Dear Syed,

I am trying to use RDT to atom map a RXN file (R3 provided below). However, both the 1.5.1 and 2.1.0 release have problems doing it. The command-line error messages from 1.5.1 is below and 2.1.0 does not return any error message. Can you point me to the possible problem with R3?

I am able to atom map several of your provided examples, so I think the code is working as intended. However, I cannot see the issue with the input file.

Regards,

Ronan

$ java -jar /usr/local/bin/rdt/rdtAlgorithm.jar -Q RXN -q "R3.rxn" -g -j AAM -f TEXT

/usr/local/bin/rdt$ ls -al
total 55220
drwxrwxr-x  3 rfleming rfleming     4096 Sep 24 17:48 .
drwxrwxrwx 28 rfleming rfleming     4096 Sep 24 15:17 ..
-rw-r--r--  1 rfleming rfleming 28240129 May 26  2017 rdt-1.5.1-SNAPSHOT-jar-with-dependencies.jar
-rw-rw-r--  1 rfleming rfleming 28278881 Oct 21  2018 rdt-2.1.0-SNAPSHOT-jar-with-dependencies.jar
lrwxrwxrwx  1 rfleming rfleming       44 Sep 24 17:48 rdtAlgorithm.jar -> rdt-2.1.0-SNAPSHOT-jar-with-dependencies.jar

!--------------------------------------------------------
Reaction Decoder Tool (RDT)

Author: Syed Asad Rahman
e-mail: asad@ebi.ac.uk
c/o EMBL-European BioInformatics Institute (EBI)
WTGC, CB10 1SD Hinxton
UK

Note: The copyright of this software belongs to the author
and EMBL-European BioInformatics Institute (EBI).

Reference
Rahman, S.A. et.al.(2016) Reaction Decoder Tool (RDT):
Extracting Features from Chemical Reactions, Bioinformatics (2016)
doi: 10.1093/bioinformatics/btw096
!--------------------------------------------------------

-- AAM --
Sep 24, 2019 5:47:25 PM uk.ac.ebi.aamtool.ChemicalFormatParser parseRXN
INFO: Annotating Reaction R3.rxn
Sep 24, 2019 5:47:25 PM uk.ac.ebi.aamtool.ReactionDecoder main
SEVERE: null
java.lang.ArrayIndexOutOfBoundsException: 10
at org.openscience.cdk.AtomContainer.getAtom(AtomContainer.java:294)
at uk.ac.ebi.reactionblast.tools.rxnfile.MDLV2000Reader.readPropertiesFast(MDLV2000Reader.java:949)
at uk.ac.ebi.reactionblast.tools.rxnfile.MDLV2000Reader.readAtomContainer(MDLV2000Reader.java:521)
at uk.ac.ebi.reactionblast.tools.rxnfile.MDLV2000Reader.read(MDLV2000Reader.java:249)
at uk.ac.ebi.reactionblast.tools.rxnfile.MDLRXNV2000Reader.readReaction(MDLRXNV2000Reader.java:333)
at uk.ac.ebi.reactionblast.tools.rxnfile.MDLRXNV2000Reader.read(MDLRXNV2000Reader.java:206)
at uk.ac.ebi.aamtool.ChemicalFormatParser.parseRXN(ChemicalFormatParser.java:97)
at uk.ac.ebi.aamtool.ReactionDecoder.AAMTask(ReactionDecoder.java:225)
at uk.ac.ebi.aamtool.ReactionDecoder.main(ReactionDecoder.java:92)

$RXN
R3

34dhphe -> dopa + co2
  1  2
$MOL
34dhphe
  Mrv1637 09261714262D          
InChIKey=WTDRDQBEARUVNC-LURJTMIESA-N
 14 14  0  0  1  0            999 V2000
    0.7145    2.0625    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145    1.2375    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289   -1.6500    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
    1.4289   -2.4750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1434   -2.8875    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
    0.7145   -2.8875    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.1434   -1.2375    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  2  7  1  0  0  0  0
  7  8  1  0  0  0  0
  5  9  1  0  0  0  0
 10  9  1  6  0  0  0
 10 11  1  0  0  0  0
 11 12  1  0  0  0  0
 11 13  2  0  0  0  0
 10 14  1  0  0  0  0
M  CHG  2  12  -1  14   1
M  END
$$$$
$MOL
dopa
  Mrv1637 09271711442D          
InChIKey=VYFYYTLLBUKUHU-UHFFFAOYSA-O
 11 11  0  0  0  0            999 V2000
    0.7145    2.0625    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145    1.2375    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -1.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -2.4750    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  2  7  1  0  0  0  0
  7  8  1  0  0  0  0
  5  9  1  0  0  0  0
  9 10  1  0  0  0  0
 10 11  1  0  0  0  0
M  CHG  1  11   1
M  END
$$$$
$MOL
co2
  Mrv1637 09271711052D          
InChIKey=CURLTUGMZLYLDI-UHFFFAOYSA-N
  3  2  0  0  0  0            999 V2000
    1.6500    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.4750    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.3000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  2  0  0  0  0
M  END
$$$$

**Comment by johnmay** [comment]
Could you block quote the molfile, please. Spaces are significant and it's hard to see if there is a formatting issue. Put ``` before and after with new lines in between.

**Comment by johnmay** [comment]
Just some more background, the error occurs at this line:

```
M CHG 1 11 1
```

But that should be fine and simply says put a +1 charge on the N. The most likely explanation is it was missing white space in the input (MOLfiles are fixed width formats). However GitHub loses this formatting unless you block quote it:

```
M CHG 1 11 1
M  CHG  1  11   1   (correct)
```

**Comment by rmtfleming** [comment]
[R3.txt](https://github.com/asad/ReactionDecoder/files/3654258/R3.txt)

**Comment by rmtfleming** [comment]
Is org.openscience.cdk.AtomContainer supposed to be in the repo?
https://github.com/asad/ReactionDecoder/tree/aa1de63743ba736bd218f4185ddc33294084ab9f/src/main/java/org/openscience/cdk

Searching for it, I get "We couldn’t find any code matching '"AtomContainer.java"' in asad/ReactionDecoder"

**Comment by johnmay** [comment]
No it's part of CDK - https://cdk.github.io/

**Comment by johnmay** [comment]
Okay the issue is the `$$$$` these normally only appear in an SDF. Take a look at the example on Page  68:
http://help.accelrysonline.com/ulm/onelab/1.0/content/ulm_pdfs/direct/reference/ctfileformats2016.pdf

Was the file made with ChemAxon or my manually sticking together the files? If I round trip though Marvin Sketch 18.10 it strips out the '$$$$'.

```
$RXN

  Mrv1810     092501192013
34dhphe -> dopa + co2
  1  2
$MOL
34dhphe
  Mrv1810 09251920132D          
InChIKey=WTDRDQBEARUVNC-LURJTMIESA-N
 14 14  0  0  1  0            999 V2000
   -3.0789    2.4750    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0789    1.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3645    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3645    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0789    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.7934    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.7934    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.5079    1.6500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0789   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3645   -1.2375    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
   -2.3645   -2.0625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6500   -2.4750    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
   -3.0789   -2.4750    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6500   -0.8250    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  2  7  1  0  0  0  0
  7  8  1  0  0  0  0
  5  9  1  0  0  0  0
 10  9  1  6  0  0  0
 10 11  1  0  0  0  0
 11 12  1  0  0  0  0
 11 13  2  0  0  0  0
 10 14  1  0  0  0  0
M  CHG  2  12  -1  14   1
M  END
$MOL
dopa
  Mrv1810 09251920132D          
InChIKey=VYFYYTLLBUKUHU-UHFFFAOYSA-O
 11 11  0  0  0  0            999 V2000
    4.3681    2.2688    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.3681    1.4438    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0825    1.0313    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0825    0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.3681   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6536    0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6536    1.0313    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.9391    1.4438    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.3681   -1.0313    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6536   -1.4437    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6536   -2.2688    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  2  7  1  0  0  0  0
  7  8  1  0  0  0  0
  5  9  1  0  0  0  0
  9 10  1  0  0  0  0
 10 11  1  0  0  0  0
M  CHG  1  11   1
M  END
$MOL
co2
  Mrv1810 09251920132D          
InChIKey=CURLTUGMZLYLDI-UHFFFAOYSA-N
  3  2  0  0  0  0            999 V2000
    6.8503    0.2438    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.6753    0.2438    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.5003    0.2438    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  2  0  0  0  0
M  END
```

**Comment by asad** [comment]
Thanks to @johnmay 
We have resolved this bug, @rmtfleming, please use version 2.3
