### ISSUE TITLE
junit test bug

### ISSUE THREAD

**Issue by asad** [asad/ReactionDecoder#2]
These cases work perfectly when executed using Netbeans 'Run Focused Method' but fails when ant test is executed

```
[junit] Testcase: R01557(aamtool.RXNMappingTest):   FAILED
[junit] expected:<2> but was:<5>
[junit] junit.framework.AssertionFailedError: expected:<2> but was:<5>
[junit]     at aamtool.RXNMappingTest.R01557(RXNMappingTest.java:121)
[junit] 
[junit] 
[junit] Testcase: R05071(aamtool.RXNMappingTest):   FAILED
[junit] expected:<2> but was:<3>
[junit] junit.framework.AssertionFailedError: expected:<2> but was:<3>
[junit]     at aamtool.RXNMappingTest.R05071(RXNMappingTest.java:1158)
```

**Comment by johnmay** [comment]
Sounds like a race condition.

**Comment by johnmay** [comment]
Trying to investigate but checkout is huge... git really isn't meant for version controlling a folder of files (rxn).

**Comment by asad** [comment]
Thank you very much John!

**Comment by asad** [comment]
Race condition: Yes this might be the cause...but each mapping call should be independent of each other...Threads are initialised when ReactionMechanismTool class call for mapping Reaction object.

**Comment by johnmay** [comment]
Adding 

``` java
return (IReaction) reaction.clone();
```

to readReactionFile fixes it.... so it's confirmed something getting clobbered. Just need to find it now.

**Comment by johnmay** [comment]
Odd because it looks like that method creates a new reaction...?

**Comment by asad** [comment]
Yes it does.

**Comment by johnmay** [comment]
Okay think I've found it will submit pull request.

**Comment by asad** [comment]
Sure thanks!

**Comment by johnmay** [comment]
Whoops I edited directly... normally that forks and the creates a pull request... forgot I had edit privileges. Anyways please check latest commit.

**Comment by asad** [comment]
No worries, at least we found the potential bug. I am not sure if this was the cause. 
Let me test it.

**Comment by asad** [comment]
I am still stuck with these three bugs (at unit level). 

Did you commit all the changes you have made at your end?

Testcase: R01557(aamtool.RXNMappingTest):	FAILED
expected:<2> but was:<5>
junit.framework.AssertionFailedError: expected:<2> but was:<5>
	at aamtool.RXNMappingTest.R01557(RXNMappingTest.java:121)


Testcase: R05071(aamtool.RXNMappingTest):	FAILED
expected:<2> but was:<3>
junit.framework.AssertionFailedError: expected:<2> but was:<3>
	at aamtool.RXNMappingTest.R05071(RXNMappingTest.java:1158)


Testcase: Rhea_25405(aamtool.RXNMappingTest):	FAILED
expected:<2> but was:<3>
junit.framework.AssertionFailedError: expected:<2> but was:<3>
	at aamtool.RXNMappingTest.Rhea_25405(RXNMappingTest.java:1252)

**Comment by johnmay** [comment]
On 3 January 2016 at 21:02, Syed Asad Rahman <notifications@github.com>
wrote:

> Did you commit all the changes you have made at your end?
>
>
Sorry no realised I left the clone in place...

Regards,
John W May
john.wilkinsonmay@gmail.com

**Comment by johnmay** [comment]
Will investigate further.

Regards,
John W May
john.wilkinsonmay@gmail.com

**Comment by asad** [comment]
Thanks, could you please commit the clone changes.

**Comment by johnmay** [comment]
On 3 January 2016 at 21:07, Syed Asad Rahman <notifications@github.com>
wrote:

> Thanks, could you please commit the clone changes.
>

Want to find the cause first...

Regards,
John W May
john.wilkinsonmay@gmail.com

**Comment by asad** [comment]
Sure thanks!

Regards,

-Asad

**Comment by johnmay** [comment]
Proving difficult to track down, the cloning was a red herring due to test order changing on recompilation. I've now managed to get a reproducible example.

If R02007 is run before R01557 it has 5 features instead of 2, R01081 is okay... as well as others.

```java
for (String reactionID : Arrays.asList("R01557", "R01081", "R01557", "R02007", "R01557")){
            ReactionMechanismTool testReactions = testReactions(reactionID, KEGG_RXN_DIR);
            IPatternFingerprinter formedCleavedWFingerprint = testReactions
                    .getSelectedSolution()
                    .getBondChangeCalculator()
                    .getFormedCleavedWFingerprint();
            System.err.println(formedCleavedWFingerprint.getFeatureCount());
        }
```

**Comment by asad** [comment]
Interesting observation! Does this mean something is being cached? I don't think different reactions would share objects but this case makes me think otherwise!

**Comment by johnmay** [comment]
Sounds like it, need to step through whats happening to see if its finding a different solution or only bond changes.

**Comment by johnmay** [comment]
Not much progress I'm afraid, I got down to `calRelation` but want to inspect the partial solutions before the GameTheoryMin... not sure where to get them from though.
