### ISSUE TITLE
-c option is giving error

### ISSUE THREAD

**Issue by killbill-del** [asad/ReactionDecoder#20]
Hello,

The option -c mentioned in the README file is not mentioned in the jar file. When I tried to run the tool with the command line in the README,it gave error. But when removed -c it was working.

There is another issue that I am facing is that when I entered the command in the README: 
java -jar rdt-2.1.0-SNAPSHOT-jar-with-dependencies.jar -Q SMI -q "CC(O)CC(=O)OC(C)CC(O)=O.O[H]>>[H]OC(=O)CC(C)O.CC(O)CC(O)=O" -g -j AAM -f TEXT
It did not generate any mapped objects. 
Here is the output. 
//
SELECTED AAM MAPPING

//
REACTANT INPUT ATOM INDEX<->AAM ID
{1=1, 2=2, 3=3, 4=4, 5=5, 6=6, 7=7, 8=8, 9=9}
PRODUCT INPUT ATOM INDEX<->AAM ID
{1=6, 2=4, 3=5, 4=2, 5=1, 6=3, 7=7, 8=8, 9=9}

The same thing happened with the reaction I submitted from my database.

Can you please help me with this?

Gopal
PS: The rdt-2.1.0-SNAPSHOT-jar-with-dependencies.jar file was taken from target folder

**Comment by asad** [comment]
java -jar rdt-2.5.0-SNAPSHOT-jar-with-dependencies.jar -Q SMI -q "CC(O)CC(=O)OC(C)CC(O)=O.O[H]>>[H]OC(=O)CC(C)O.CC(O)CC(O)=O" -g -j AAM -f TEXT

![ECBLAST_smiles_AAM](https://user-images.githubusercontent.com/66897/110054422-f79d3f00-7d52-11eb-9584-4d3153dd4272.png)
[ECBLAST_smiles_AAM.txt](https://github.com/asad/ReactionDecoder/files/6087605/ECBLAST_smiles_AAM.txt)

**Comment by asad** [comment]
REACTANT INPUT ATOM INDEX<->AAM ID
This option is now obsolete and will be removed in the future releases.

**Comment by killbill-del** [comment]
Thank you for your reply. :)
