### ISSUE TITLE
Code doesn't build

### ISSUE THREAD

**Issue by johnmay** [asad/ReactionDecoder#5]
There are two BondChangeCalculator!

**Comment by asad** [comment]
Fixed, btw. v2.0 is unstable

**Comment by johnmay** [comment]
Okay, for future reference you should use 2.0-SNAPSHOT (preferred) or 2.0alpha for "unstable" versions. Also unstable usually means the API changes from release to release not that it doesn't work (compile), that would just be "v2.0 is broken" :-).

**Comment by asad** [comment]
Thanks, it should compile. 
Indeed I am making some major API changes hence its unstable (Mavinised) :-)
I think its named a 2.0-SNAPSHOT but I will make it explicit.
