### ISSUE TITLE
The "-u" flag in Compare functionality

### ISSUE THREAD

**Issue by benbowen** [asad/ReactionDecoder#6]
We are thoroughly enjoying the use of your tools, but can't get something to work as we expected.  We have a list of reactions that we have performed "Annotate" on.  Now we are using the "Compare" tool.  It seems like it always recalculates the annotation even if we use the -u flag.  

Starting with the example in README.md

```
java -jar ReactionDecoder.jar -Q SMI -q "CC(O)CC(=O)OC(C)CC(O)=O.O[H]>>[H]OC(=O)CC(C)O.CC(O)CC(O)=O" -g -j ANNOTATE -f XML
```

This works, and makes ECBLAST_smiles_ANNONATE xml and rxn

Trying the comparison as is in README.md

```
java -jar ReactionDecoder.jar -Q RXN -q ECBLAST_smiles_ANNONATE.rxn  -T RXN -t ECBLAST_smiles_ANNONATE.rxn -j COMPARE -f BOTH -u
```

This annotates and throws a severe: null pointer exception.

Trying it with reaction mapped reaction string completes, but calculates the annotation step.

```
java -jar ReactionDecoder.jar -Q SMI -q "[O:1]=[C:2]([OH:3])[CH2:4][CH:5]([O:6][C:7](=[O:8])[CH2:9][CH:10]([OH:11])[CH3:12])[CH3:13].[OH2:14]>>[CH:5]([OH:6])([CH3:13])[CH2:4][C:2]([O:3][H:16])=[O:1].[CH2:9]([CH:10]([OH:11])[CH3:12])[C:7]([OH:14])=[O:8]" -T SMI -t "[O:1]=[C:2]([OH:3])[CH2:4][CH:5]([O:6][C:7](=[O:8])[CH2:9][CH:10]([OH:11])[CH3:12])[CH3:13].[OH2:14]>>[CH:5]([OH:6])([CH3:13])[CH2:4][C:2]([O:3][H:16])=[O:1].[CH2:9]([CH:10]([OH:11])[CH3:12])[C:7]([OH:14])=[O:8]" -j COMPARE -f BOTH -u
```

It seems that the -u flag would need the xml information to fully map.  How can I run COMPARE without the tool recalculating annotations?

**Comment by benbowen** [comment]
If no one is able to work on this right now, I can try and recruit some java people from here to help kill this bug.  I don't want to dive in if someone else already knows exactly what's wrong.

**Comment by johnmay** [comment]
Should be an easy fix but I can't get the project to compile at all (duplicate class names). That needs to be fixed first.

**Comment by asad** [comment]
I have released version 1.4.1 which should fix the -u bug.

**Comment by benbowen** [comment]
I think a minor error might have been introduced with 1.4.1.  Using the reaction SMILES for pyruvate dehydrogenase, I can successfully make the annotation files using:
```
java -jar RDT1.4.1.jar -Q SMI -q "CC(C)(COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12)[C@@H](O)C(=O)NCCC(=O)NCCS.CC(=O)C([O-])=O.NC(=O)c1ccc[n+](c1)[C@@H]1O[C@H](COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](OP([O-])([O-])=O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O>>NC(=O)C1=CN(C=CC1)[C@@H]1O[C@H](COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](OP([O-])([O-])=O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O.O=C=O.CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12" -g -j ANNOTATE -f XML
```
However, when I try to compare the reactions (to self):
```
java -jar RDT1.4.1.jar -Q RXN -q ECBLAST_smiles_ANNONATE.rxn -T RXN -t ECBLAST_smiles_ANNONATE.rxn -j COMPARE -f BOTH -u
```
I get:
```
SEVERE: null
org.openscience.cdk.exception.CDKException: 
ERROR: Unable to calculate bond changes: 
ERROR: Unable to calculate bond changes: One or more atoms had an undefined number of implicit hydrogens
	at uk.ac.ebi.reactionblast.mechanism.ReactionMechanismTool.<init>(ReactionMechanismTool.java:152)
	at uk.ac.ebi.aamtool.Annotator.getReactionMechanismTool(Annotator.java:130)
	at uk.ac.ebi.aamtool.ReactionDecoder.CompareTask(ReactionDecoder.java:404)
	at uk.ac.ebi.aamtool.ReactionDecoder.main(ReactionDecoder.java:101)

```

Using the old jar file I can successfully compare using the reaction file I just made, but have to omit the -u flag.
```
java -jar ReactionDecoder.jar -Q RXN -q ECBLAST_smiles_ANNONATE.rxn -T RXN -t ECBLAST_smiles_ANNONATE.rxn -j COMPARE -f BOTH
```
Takes a while because its presumably annotating the reactions, but finishes with no errors.

**Comment by johnmay** [comment]
@benbowen The RXN file being produce is invalid and uses aromatic bond types (a big no-no on CTfiles!). The default is overridden here:

https://github.com/asad/ReactionDecoder/blob/54e7d893678d29370d61a40b8e041b186a2270bb/RDT1.4/src/uk/ac/ebi/reactionblast/tools/rxnfile/MDLV2000RXNWriter.java#L362-L363

I would say use SMILES but it looks like that is also being corrupted:

```[O:1]=[C:2]([NH:3][CH2:4][CH2:5][SH:6])[CH2:7][CH2:8][NH:9][C:10](=[O:11])[CH:12]([OH:13])[C:14]([CH3:15])([CH3:16])[CH2:17][O:18][P:19](=[O:20])([O-:21])[O:22][P:23](=[O:24])([O-:25])[O:26][CH2:27][CH:28]1[O:29][CH:30]([N:31]:2:[CH:32]:[N:33]:[C:34]:3:[C:35](:[N:36]:[CH:37]:[N:38]:[C:39]23)[NH2:40])[CH:41]([OH:42])[CH:43]1[O:44][P:45](=[O:46])([O-:47])[O-:48].[O:49]=[C:50]([NH2:51])[C:52]:1:[CH:53]:[CH:54]:[CH:55]:[N+:56](:[CH:57]1)[CH:58]2[O:59][CH:60]([CH2:61][O:62][P:63](=[O:64])([O-:65])[O:66][P:67](=[O:68])([O-:69])[O:70][CH2:71][CH:72]3[O:73][CH:74]([N:75]:4:[CH:76]:[N:77]:[C:78]:5:[C:79](:[N:80]:[CH:81]:[N:82]:[C:83]45)[NH2:84])[CH:85]([O:86][P:87](=[O:88])([O-:89])[O-:90])[CH:91]3[OH:92])[CH:93]([OH:94])[CH:95]2[OH:96].[O:97]=[C:98]([O-:99])[C:100](=[O:101])[CH3:102]&gt;&gt;[O-:48][P:45]([O-:47])([O:44][CH:43]1[CH:28]([CH2:27][O:26][P:23]([O:22][P:19]([O:18][CH2:17][C:14]([CH:12]([C:10]([NH:9][CH2:8][CH2:7][C:2]([NH:3][CH2:4][CH2:5][S:6][C:100](=[O:101])[CH3:102])=[O:1])=[O:11])[OH:13])([CH3:15])[CH3:16])(=[O:20])[O-:21])(=[O:24])[O-:25])[O:29][CH:30]([N:31]:2:[CH:32]:[N:33]:[C:34]:3:[C:35](:[N:36]:[CH:37]:[N:38]:[C:39]23)[NH2:40])[CH:41]1[OH:42])=[O:46].[O:49]=[C:50]([NH2:51])[C:52]=1[CH2:53][CH:54]=[CH:55][N:56]([CH:57]1)[CH:58]2[O:59][CH:60]([CH2:61][O:62][P:63](=[O:64])([O-:65])[O:66][P:67](=[O:68])([O-:69])[O:70][CH2:71][CH:72]3[O:73][CH:74]([N:75]:4:[CH:76]:[N:77]:[C:78]:5:[C:79](:[N:80]:[CH:81]:[N:82]:[C:83]45)[NH2:84])[CH:85]([O:86][P:87](=[O:88])([O-:89])[O-:90])[CH:91]3[OH:92])[CH:93]([OH:94])[CH:95]2[OH:96].[O:97]=[C:98]=[O:99]```

**Comment by asad** [comment]
Thanks @benbowen and @johnmay 
I have updated the code and switching off the aromatic bond writer does the trick. Perhaps this was a legacy feature form OLD CDK code. Please test the updated 1.4.1 jar file

![example](https://cloud.githubusercontent.com/assets/66897/20096220/c7391e94-a5a0-11e6-82e6-a8729897594a.png)

**Comment by asad** [comment]
The SMILES appears to be "corrupted" as ">>" signs are interpreted as &gt;&gt

**Comment by johnmay** [comment]
@asad Yes but that wasn't what I meant... look at the aromatic rings. You're writing benzene as
`C1:C:C:C:C:C1` instead of `c1ccccc1`. Most likely what is happen is you're clearing aromaticity on the atoms and not the bonds.

**Comment by johnmay** [comment]
`C:1:C:C:C:C:C1` is valid but is cyclo hexane not benzene.

**Comment by asad** [comment]
I see, any pointers where this is happening? The image file looks good to me....perhaps somewhere after this process?

**Comment by johnmay** [comment]
Well the best fix is just not write aromatic SMILES, why do you think it's
a good idea?

https://github.com/asad/ReactionDecoder/blob/6a2fe34c22e55875e55d49ef903c10ee1e91923c/development/rdt/tools/src/main/java/uk/ac/ebi/reactionblast/tools/CDKSMILES.java#L130

Otherwise you'll have to track it down, atom typing is usual candidate but
Egon changed that recently.

John

**Comment by asad** [comment]
The reason we are using aromatic bond changes in SMILES is for the ease of users. This helps them clearly see and judge bond changes (no every user is a chemist). 

Do you reckon that atom typing would fix this (pasting the same SMILES in the ChemAxon gave me correct output i.e. benzene...I am sure there is a way to fix them :-) )? 

Alternately I could comment https://github.com/asad/ReactionDecoder/blob/6a2fe34c22e55875e55d49ef903c10ee1e91923c/development/rdt/tools/src/main/java/uk/ac/ebi/reactionblast/tools/CDKSMILES.java#L130

**Comment by johnmay** [comment]
> The reason we are using aromatic bond changes in SMILES is for the ease of users. This helps them clearly see and judge bond changes (not every user is a chemist).

But thats independent of the storage format, you really should always write SMILES as Kekulé for portability. For depiction and calculation you can always delocalise again. Many toolkits have poor kekulization algorithms (See Slide 47: http://www.slideshare.net/NextMoveSoftware/substructure-search-faceoff) and the only way to ensure portability is to write the bond orders in.

CDK follows the Daylight, arguably correct, semantics. Aromaticity is primarily an atom property in SMILES. Either way that SMILES is just plain wrong... i think I might have actually made it throw an exception in new versions.

I did not say add atom typing... but remove it if there is any.  The (now fixed) problem was here:
https://github.com/cdk/cdk/commit/0dda78a7bb4b222d794fd6f6f22b7ce9e5c9a5ff
Notice the aromaticity flags get wiped by the atom type.

Probably not the cause but this is wrong here: 
https://github.com/asad/ReactionDecoder/blob/a7f2f22861dd4cf46097d4131cbefc6d216c082c/RDT1.4/src/org/openscience/smsd/filters/EnergyFilter.java#L131
You can't create custom flags, it needs to be a property and a power of 2 (999 is not)! Granted this should be an enum but your setting the flag to 999 is undefined behaviour.

**Comment by asad** [comment]
@johnmay thanks for your comments. Looks like updating it to the new CDK might overcome this problem. In the meanwhile I will write them in Kekulé format.

**Comment by asad** [comment]
@benbowen The jar has been updated please test it.

**Comment by benbowen** [comment]
Thanks both for the rapid and thoughtful solution!!!  It seems good for a couple test cases.

```
java -jar RDT1.4.1.jar -Q SMI -q "CC(C)(COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12)[C@@H](O)C(=O)NCCC(=O)NCCS.CC(=O)C([O-])=O.NC(=O)c1ccc[n+](c1)[C@@H]1O[C@H](COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](OP([O-])([O-])=O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O>>NC(=O)C1=CN(C=CC1)[C@@H]1O[C@H](COP([O-])(=O)OP([O-])(=O)OC[C@H]2O[C@H]([C@H](OP([O-])([O-])=O)[C@@H]2O)n2cnc3c(N)ncnc23)[C@@H](O)[C@H]1O.O=C=O.CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP([O-])(=O)OP([O-])(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP([O-])([O-])=O)n1cnc2c(N)ncnc12" -g -j ANNOTATE -f XML
```
Generates rxn file that preserves aromatics.
```
java -jar RDT1.4.1.jar -Q RXN -q ECBLAST_smiles_ANNONATE.rxn -T RXN -t ECBLAST_smiles_ANNONATE.rxn -j COMPARE -f BOTH -u
```
Does the comparison without re-annotating!  Thanks!!!
